/**
 * Portfolio projects — the language-independent facts.
 *
 * Localized copy (industry, summary, case-study text) lives in
 * src/content/work/<lang>/<key>.yaml. The `key` links the two.
 *
 * Rules for this file:
 *  - Only real, delivered projects.
 *  - No invented metrics. Add `results` in the YAML files only when the client has
 *    measured them and agreed to publish them.
 *  - Screenshots are generated by `npm run screenshots` into src/assets/work/<key>/.
 */
import type { ServiceKey } from './services';

export type WorkCategory = 'web' | 'branding' | 'ecommerce' | 'marketing' | 'seo' | 'multilingual' | 'healthcare' | 'corporate' | 'media' | 'nonprofit';

export interface Project {
  /** Projects that belong to the same client group are cross-linked on case studies. */
  group?: string;
  key: string;
  client: string;
  /** Live website, also used by the screenshot script. */
  url?: string;
  /** Profile link for clients without a website (e.g. Instagram). */
  profile?: string;
  /** Services delivered — keys from src/data/services.ts. */
  services: ServiceKey[];
  /** Used by the filter on the Work page. */
  categories: WorkCategory[];
  /** Platform / stack as actually used on the live project. */
  technologies: string[];
  /** Languages the delivered site is published in (ISO codes). */
  siteLanguages?: string[];
  year?: number;
  /** The client's brand colour — used for covers and accents on the case study. */
  brand: string;
  /** Feature on the home page (order = position). */
  featured?: number;
  /** Order on the Work page. */
  order: number;
}

export const projects: Project[] = [
  {
    key: 'medicus-center',
    client: 'MEDICUS Dental Clinic',
    url: 'https://www.medicuscenter.al/',
    services: ['web-design-development', 'seo', 'paid-ads', 'social-media-marketing'],
    categories: ['web', 'seo', 'marketing', 'multilingual', 'healthcare'],
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS', 'next-intl', 'PHP mailer', 'GA4 (consent-gated)', 'Schema.org'],
    siteLanguages: ['en', 'sq', 'it', 'de'],
    brand: '#1B3A6B',
    featured: 1,
    order: 1,
  },
  {
    key: 'scidev',
    client: 'SCiDEV',
    url: 'https://scidevcenter.org/',
    services: ['web-design-development', 'seo', 'paid-ads', 'social-media-marketing'],
    categories: ['web', 'seo', 'marketing', 'nonprofit'],
    technologies: ['WordPress', 'WPBakery', 'Custom theme styling'],
    group: 'SCiDEV',
    brand: '#273272',
    featured: 2,
    order: 2,
  },
  {
    key: 'ir-real-estate',
    group: 'Finman Group',
    client: 'IR Real Estate & Management',
    url: 'https://ir.al/',
    services: ['web-design-development', 'seo', 'paid-ads', 'social-media-marketing'],
    categories: ['web', 'seo', 'marketing', 'corporate'],
    technologies: ['WordPress', 'WooCommerce', 'WPBakery'],
    brand: '#FE6C61',
    featured: 3,
    order: 3,
  },
  {
    key: 'albstar',
    group: 'Finman Group',
    client: 'Albstar',
    url: 'https://albstar.al/',
    services: ['web-design-development', 'seo', 'paid-ads', 'social-media-marketing'],
    categories: ['web', 'seo', 'marketing', 'multilingual', 'corporate'],
    technologies: ['WordPress', 'Custom theme', 'qTranslate-X', 'WPBakery'],
    siteLanguages: ['sq', 'en'],
    brand: '#021B70',
    featured: 4,
    order: 4,
  },
  {
    key: 'finman',
    group: 'Finman Group',
    client: 'Finman Group',
    url: 'https://finman.al/',
    services: ['web-design-development', 'seo', 'paid-ads', 'social-media-marketing'],
    categories: ['web', 'seo', 'marketing', 'corporate'],
    technologies: ['WordPress', 'WooCommerce', 'WPBakery'],
    brand: '#002E5B',
    order: 6,
  },
  {
    key: 'fintrade',
    group: 'Finman Group',
    client: 'Fintrade',
    url: 'https://fintrade.al/',
    services: ['web-design-development', 'seo', 'paid-ads', 'social-media-marketing'],
    categories: ['web', 'seo', 'marketing', 'multilingual', 'corporate'],
    technologies: ['WordPress', 'WPBakery'],
    siteLanguages: ['sq', 'en'],
    brand: '#273272',
    order: 7,
  },
  {
    key: 'elbasanion',
    client: 'ElbasaniON',
    url: 'https://elbasanion.al/new/',
    services: ['web-design-development', 'seo', 'paid-ads', 'social-media-marketing'],
    categories: ['web', 'seo', 'marketing', 'media'],
    technologies: ['WordPress', 'Custom PHP theme', 'Vanilla JavaScript', 'WordPress Customizer'],
    siteLanguages: ['sq'],
    brand: '#DD0917',
    order: 5,
  },
  {
    key: 'eydr',
    client: 'EYDR',
    url: 'https://eydr.scidevcenter.org/',
    group: 'SCiDEV',
    services: ['web-design-development', 'seo', 'paid-ads', 'social-media-marketing'],
    categories: ['web', 'seo', 'marketing', 'nonprofit'],
    technologies: ['WordPress', 'Elementor'],
    brand: '#093C8E',
    order: 8,
  },
  {
    key: 'albanian-athletes',
    client: 'Albanian Athletes Group',
    url: 'https://albanianathletesgroup.com/',
    services: ['web-design-development', 'seo', 'paid-ads', 'social-media-marketing'],
    categories: ['web', 'seo', 'marketing', 'nonprofit'],
    technologies: ['WordPress', 'WPBakery', 'Google Site Kit'],
    brand: '#E30613',
    order: 9,
  },
  {
    key: 'implant-swiss-albania',
    client: 'Implant Swiss Albania',
    profile: 'https://www.instagram.com/implantswissalbania/',
    services: ['social-media-marketing', 'paid-ads'],
    categories: ['marketing', 'healthcare'],
    technologies: ['Meta Business Suite', 'Meta Ads'],
    brand: '#0A7CBF',
    order: 10,
  },
];

export const projectByKey = (key: string) => projects.find((p) => p.key === key);
export const sortedProjects = [...projects].sort((a, b) => a.order - b.order);
export const featuredProjects = projects
  .filter((p) => p.featured)
  .sort((a, b) => (a.featured ?? 0) - (b.featured ?? 0));

/**
 * Client logos (public/clients/<key>.webp) for the logo strip. Project clients link to their
 * case study; logo-only clients are shown without a link until there is more to show.
 */
export interface ClientLogo {
  key: string;
  client: string;
  /** Project key when there is a case study. */
  project?: string;
  /** Logo artwork is light (made for dark backgrounds) → shown on a dark tile. */
  dark?: boolean;
}

export const clientLogos: ClientLogo[] = [
  { key: 'medicus', client: 'MEDICUS Dental Clinic', project: 'medicus-center' },
  { key: 'scidev', client: 'SCiDEV', project: 'scidev' },
  { key: 'ir', client: 'IR Real Estate & Management', project: 'ir-real-estate' },
  { key: 'albstar', client: 'Albstar', project: 'albstar' },
  { key: 'elbasanion', client: 'ElbasaniON', project: 'elbasanion' },
  { key: 'finman', client: 'Finman Group', project: 'finman' },
  { key: 'fintrade', client: 'Fintrade', project: 'fintrade' },
  { key: 'eydr', client: 'EYDR', project: 'eydr' },
  { key: 'albanian-athletes', client: 'Albanian Athletes Group', project: 'albanian-athletes' },
  { key: 'implant-swiss', client: 'Implant Swiss Albania', project: 'implant-swiss-albania', dark: true },
  { key: 'arena-center', client: 'Arena Center' },
  { key: 'altana', client: 'ALTANA Luxury Residence' },
  { key: 'tirana-factoring', client: 'Tirana Factoring & Lease' },
  { key: 'impact', client: 'Impact SHPK' },
  { key: 'smileprovider', client: 'SmileProvider Clinic' },
  { key: 'newdent', client: 'NewDent Clinic' },
  { key: 'subashi-dental', client: 'Subashi Dental Clinic' },
  { key: 'souvlaki-station', client: 'Souvlaki Station' },
  { key: 'aksoy', client: 'Aksoy Hukuk Bürosu' },
];
